AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend deployment with S3
Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebsiteURL:
    Description: "URL for the website"
    Value: !GetAtt FrontendBucket.WebsiteURL
